### ISSUE TITLE
自从开放自定义风格设置后，请看这样如何？

### ISSUE THREAD

**Issue by nstylec** [zenghongtu/Mob#12]
### 我猜作者想要一个绿色为主色调的清新小软件，那么这么改好看吗？

目前对界面的建议: 
1. 载入的loading bar可以做的更精美些，也许圆角可以为暂时解决方案
2. mob的logo和主界面的色调完全不符啊…求改进

[![2019-05-21-12-21-22.png](https://i.postimg.cc/QC8P7RJJ/2019-05-21-12-21-22.png)](https://postimg.cc/KkWJSpV1)

**Comment by zenghongtu** [comment]
哈，谢谢你的建议，logo 色调确实不太符，这是个大问题，我先把 logo改了，loading bar考虑之后来个大改
