### ISSUE TITLE
(Win) 首页无数据, 推荐无数据, 第三方无法登陆, 没有托盘驻留么?

### ISSUE THREAD

**Issue by cryzlasm** [zenghongtu/Mob#13]
**请先确认是否为[最新版本](https://github.com/zenghongtu/Mob/releases/latest)**

#### 问题描述
启动白屏
首页无数据, 
推荐无数据, 
第三方无法登陆, 
没有托盘驻留么?(没有关闭或者缩小按钮, alt+f4 直接退出了)
#### 截图（可选）
![image](https://user-images.githubusercontent.com/20424580/58149401-55ca6200-7c52-11e9-9b18-5c57f852e7c6.png)
![image](https://user-images.githubusercontent.com/20424580/58149409-5a8f1600-7c52-11e9-9357-dfce9bf8bdfc.png)
![image](https://user-images.githubusercontent.com/20424580/58149412-611d8d80-7c52-11e9-8c19-afe0fc233ddb.png)
![image](https://user-images.githubusercontent.com/20424580/58149417-67136e80-7c52-11e9-8661-21ee8832331b.png)
![image](https://user-images.githubusercontent.com/20424580/58149454-87432d80-7c52-11e9-9d18-2f36f0889992.png)

**Comment by zenghongtu** [comment]
看了一下，是官网挂了额额。

![image](https://user-images.githubusercontent.com/25629121/58150795-4969f780-7c9a-11e9-8803-369a1458b3f3.png)

第三方登陆还在想办法中，托盘我去看一下 api 加上

**Comment by cryzlasm** [comment]
首页挂了,可真的厉害了, 要跑路了么..

**Comment by cryzlasm** [comment]
对了, 会改一下单例模式么?

**Comment by cryzlasm** [comment]
![image](https://user-images.githubusercontent.com/20424580/58156180-0ccfd900-7c65-11e9-97fc-ab8b3ab2a700.png)
