### ISSUE TITLE
Mac版本今天打开之后所有内容都没有了

### ISSUE THREAD

**Issue by kwgao** [zenghongtu/Mob#14]
**请先确认是否为[最新版本](https://github.com/zenghongtu/Mob/releases/latest)**

#### 问题描述
<img width="1024" alt="屏幕快照 2019-05-22 下午2 28 21" src="https://user-images.githubusercontent.com/50562384/58151972-e1b5ab80-7c9d-11e9-85a3-ffdbd23a74af.png">

**Comment by kwgao** [comment]
刚看到微博热搜说是喜马拉雅机房崩了。。。

**Comment by Jonnyan404** [comment]
window版本也空白了

**Comment by yinxin630** [comment]
喜马拉雅跪了.. 23333
