### ISSUE TITLE
mac命令安装提示没有mob

### ISSUE THREAD

**Issue by journeyOS** [zenghongtu/Mob#15]
brew cask install mob
Error: Cask 'mob' is unavailable: No Cask with this name exists.

**Comment by zenghongtu** [comment]
![image](https://user-images.githubusercontent.com/25629121/58228764-50f4d380-7d62-11e9-8533-b562a67b9cf8.png)

我试了一下没有问题哈。

 ps: 安装前要等它先更新完。
