### ISSUE TITLE
win下的字体显示效果有点儿难受啊👀

### ISSUE THREAD

**Issue by jon-zhang** [zenghongtu/Mob#16]
### 描述
希望开发者大大可以优化优化

### 截图（可选）
![image](https://user-images.githubusercontent.com/39263812/58185058-e2bdfb80-7ce4-11e9-8bc4-e9cdab86a9b3.png)

**Comment by csx43600121** [comment]
建议开发者换成免费字体  注意版权问题

**Comment by zenghongtu** [comment]
发布了一个版本，更新了字体，可以下载来试试看
