### ISSUE TITLE
源码执行： yarn run start:main 出现问题

### ISSUE THREAD

**Issue by helinyu** [zenghongtu/Mob#18]
通过源码运行
#### 问题描述
执行：  yarn run start:main 

#### 截图（可选）
![Snip20190523_14](https://user-images.githubusercontent.com/6794638/58241407-82c86300-7d7f-11e9-8fe0-c6af3c2a25c2.png)

**Comment by zenghongtu** [comment]
这个不影响的，它现在报的错误指向的是 renderer 进程目录。是由于 main 进程 tsconfig 的设置问题。
