### ISSUE TITLE
如何关闭全局快捷键

### ISSUE THREAD

**Issue by huifeidegezi** [zenghongtu/Mob#2]
如何关闭快捷键啊？

**Comment by yinxin630** [comment]
同求, 希望支持mac的媒体按钮(播放/暂停, 前进, 后退)
现在的全局快捷键和chrome的标签页左右切换冲突了, 很难受

**Comment by zenghongtu** [comment]
额，这个之前没想那么多，写死了。
今晚发布一个小版本更新一下，添加快捷键开关
