### ISSUE TITLE
为什么我在网页无法看到效果?

### ISSUE THREAD

**Issue by TRUEJASONFANS** [zenghongtu/Mob#21]
**请先确认是否为[最新版本](https://github.com/zenghongtu/Mob/releases/latest)**

#### 问题描述
运行 yarn run start
#### 截图（可选）
<img width="1380" alt="屏幕快照 2019-05-29 上午12 40 34" src="https://user-images.githubusercontent.com/5670289/58495672-a558e280-81aa-11e9-8298-454ed2b42bfc.png">

**Comment by zenghongtu** [comment]
要注入 node 和 electron 依赖，用浏览器打开是会报错的哈。

**Comment by TRUEJASONFANS** [comment]
@zenghongtu  ok
