### ISSUE TITLE
yarn start 不能正常启动项目，报警告 Module not found: Error: Can't resolve 'worker_threads' in '/Users/andy/vscode/Mob/node_modules/write-file-atomic'

### ISSUE THREAD

**Issue by Yashiro** [zenghongtu/Mob#5]
版本:
v0.1.4

描述：
执行 yarn start，报如下警告
Module not found: Error: Can't resolve 'worker_threads' in '/Users/andy/vscode/Mob/node_modules/write-file-atomic'

node ver 10.15.3
yarn ver 1.16.0

具体现象是无法正常出现 electron 的界面，望得到作者的解答

截图：
![Xnip2019-05-15_16-36-10](https://user-images.githubusercontent.com/5180632/57761509-40c07100-7730-11e9-8c22-a4fbb83821ef.jpg)
![Xnip2019-05-15_16-36-43](https://user-images.githubusercontent.com/5180632/57761511-40c07100-7730-11e9-9bac-efb88485412f.jpg)

**Comment by zenghongtu** [comment]
这个是因为依赖库 electron-store 的问题，它用到了一个新特性，升级 node 12 就不会有这个错误了。不升级也不影响的

**Comment by Yashiro** [comment]
electron 全局安装 yarn start 不出现界面时再 electron reload 一下？

**Comment by zenghongtu** [comment]
不是的，在打开的 electron reload 一下。
或者你先运行` yarn run start:renderer`等编译完成，在运行` yarn run start:main`。

**Comment by Yashiro** [comment]
但这样 console 会报很多 error 不知是否与这种启动方式有关，如图
![Xnip2019-05-15_21-15-50](https://user-images.githubusercontent.com/5180632/57778491-c0613680-7756-11e9-9d00-c6e8b0222f1f.jpg)
还是 node 版本过低了，要从 10 升级到 12 才行

**Comment by Yashiro** [comment]
我升级了 node 到 v 12 版本，不再报警告了，但是执行 yarn start 还是不会默认启动 electron 界面，我看了 package.json 的 start 命令 应该是先启动 renderer 再启动 main，为什么不会执行后面的 start:main，望告知

**Comment by Yashiro** [comment]
另外我第二次发的图的问题，还是依然存在，没有因 node 升级到 v12 而消失

**Comment by zenghongtu** [comment]
这些是 ts 的类型错误，不影响的

**Comment by LanjianNUll** [comment]
> 我升级了 node 到 v 12 版本，不再报警告了，但是执行 yarn start 还是不会默认启动 electron 界面，我看了 package.json 的 start 命令 应该是先启动 renderer 再启动 main，为什么不会执行后面的 start:main，望告知

package.json的script 脚本是 Shell ， &&  只有前一个任务成功，才执行下一个任务， 这里的成功应该是shell 返回0，也就是上一条命令执行的返回值，如果为0则代表执行成功

**Comment by LanjianNUll** [comment]
请教下：
node: v10.15.1
运行 yarn run start:renderer等编译完成，在运行 yarn run start:main 
electron 界面 503  ，ctrl+r ,无效 
网页打开 localhost:6008/: 有界面 ，这是什么缘故

**Comment by LanjianNUll** [comment]
![捕获](https://user-images.githubusercontent.com/15379422/57786094-76338180-7765-11e9-840b-2141f4c96bd8.PNG)

**Comment by zenghongtu** [comment]
> 请教下：
> node: v10.15.1
> 运行 yarn run start:renderer等编译完成，在运行 yarn run start:main
> electron 界面 503 ，ctrl+r 无反应
> 网页打开 localhost:6008/: 有界面 ，这是什么缘故

网页打得开，那就是 electron 的问题。必须用 hash router，正确地址应该是  localhost:6008/#/

**Comment by Yashiro** [comment]
> 这些是 ts 的类型错误，不影响的

想问一下，你这边启动也有这些 ts error 吗，是如何设置的？需要额外安装什么插件吗？这样也可以让 yarn start 命令里 && 之前的返回正确正常执行之后的命令，自动跳出 electron。另外还想问一下，这种情况下如何开启 chrome 调试

**Comment by zenghongtu** [comment]
ts error 这些是 main 进程（electron）的 tsconfig 设置问题，路径里面包括到了 renderer 进程，也就是 src/renderer 里面的内容导致的。可以去看一下 electron-webpack 的 repo 文档，我懒得看了就没改。可以改好了发个 pr 。那个 yarn start 是有点问题，要用`concurrently`启动，我有时间改一下吧。推荐两个分开运行吧，这个样好做改动一些。
