### ISSUE TITLE
项目运行不起来

### ISSUE THREAD

**Issue by illmm** [zenghongtu/Mob#7]
### 描述
怎么样能把项目运行起来呀。v0.1.3、v0.1.5、master 都试了 都运行不起来
### 截图（可选）
![image](https://user-images.githubusercontent.com/26830376/57841989-34a2e500-77fe-11e9-8b4c-32df62caa34f.png)
![image](https://user-images.githubusercontent.com/26830376/57842081-66b44700-77fe-11e9-9c05-6d2a7e6eb5e8.png)

**Comment by zenghongtu** [comment]
其他分支可能有问题的，就运行 master 分支就好了。白屏的话，cmd + r 刷新一下，如果不行就是 renderer 进程没有起来。
